const WRITTEN_COLORS=['#2878c8','#8b5cf6','#15a06b','#e29b20','#df5b57','#537188'];
const PRACTICAL_COLORS=['#0f766e','#c2410c','#7c3aed'];
const DEF={
  startDate:'2026-07-01',examDate:'2027-01-01',practicalStartDate:null,
  subjects:[
    {id:'hydro',name:'수리수문학',theoryTotal:45,per:3,day:0,color:WRITTEN_COLORS[0],targetRounds:1,specialTotal:3,coreTotal:6},
    {id:'soil',name:'토질 및 기초',theoryTotal:46,per:3,day:0,color:WRITTEN_COLORS[1],targetRounds:1,specialTotal:3,coreTotal:6},
    {id:'water',name:'상하수도공학',theoryTotal:29,per:2,day:1,color:WRITTEN_COLORS[2],targetRounds:1,specialTotal:0,coreTotal:6},
    {id:'survey',name:'측량학',theoryTotal:42,per:3,day:1,color:WRITTEN_COLORS[3],targetRounds:1,specialTotal:3,coreTotal:6},
    {id:'mech',name:'응용역학',theoryTotal:53,per:3,day:2,color:WRITTEN_COLORS[4],targetRounds:1,specialTotal:0,coreTotal:10},
    {id:'struct',name:'철근콘크리트 및 강구조',theoryTotal:null,per:3,day:2,color:WRITTEN_COLORS[5],targetRounds:1,specialTotal:0,coreTotal:6}
  ],
  practicalSubjects:[
    {id:'quantity',name:'토목적산(물량산출)',theoryTotal:14,coreTotal:3,per:3,day:0,color:PRACTICAL_COLORS[0]},
    {id:'construction',name:'토목시공',theoryTotal:46,coreTotal:6,per:3,day:1,color:PRACTICAL_COLORS[1]},
    {id:'process',name:'토목공정(공정 및 품질관리)',theoryTotal:19,coreTotal:2,per:3,day:2,color:PRACTICAL_COLORS[2]}
  ],
  checks:{},reviews:{},notes:{},restDays:[],postponedDates:{}
};
const K='civilPlannerWeb1',$=id=>document.getElementById(id),pad=n=>String(n).padStart(2,'0');
function clone(x){return JSON.parse(JSON.stringify(x))}
function normalizeCheckValue(v){return v&&typeof v==='object'?v:{checkedAt:null,studyDate:null}}
function migrateChecks(checks){const out={};Object.entries(checks||{}).forEach(([k,v])=>{
  let m=k.match(/^([^:]+):(\d+)$/);if(m){out[`w:${m[1]}:theory:r1:l${m[2]}`]=normalizeCheckValue(v);return}
  m=k.match(/^([^:]+):r(\d+):l(\d+)$/);if(m){out[`w:${m[1]}:theory:r${m[2]}:l${m[3]}`]=normalizeCheckValue(v);return}
  out[k]=normalizeCheckValue(v);
});return out}
function mergeWritten(raw){return (raw.subjects||clone(DEF.subjects)).map((s,i)=>{
  const d=DEF.subjects[i]||{};
  return {...clone(d),...s,theoryTotal:s.theoryTotal??s.total??d.theoryTotal,color:s.color||d.color,targetRounds:Math.max(1,Number(s.targetRounds)||1),specialTotal:s.specialTotal??d.specialTotal,coreTotal:s.coreTotal??d.coreTotal};
})}
function mergePractical(raw){return (raw.practicalSubjects||clone(DEF.practicalSubjects)).map((s,i)=>({...clone(DEF.practicalSubjects[i]),...s}))}
let S=(()=>{try{const raw=JSON.parse(localStorage.getItem(K));if(!raw)return clone(DEF);return {...clone(DEF),...raw,subjects:mergeWritten(raw),practicalSubjects:mergePractical(raw),checks:migrateChecks(raw.checks),reviews:raw.reviews||{},notes:raw.notes||{},restDays:raw.restDays||[],postponedDates:raw.postponedDates||{},practicalStartDate:raw.practicalStartDate||null}}catch{return clone(DEF)}})();
let selectedDate=iso(new Date());
const save=()=>localStorage.setItem(K,JSON.stringify(S));
function date(s){const[a,b,c]=s.split('-').map(Number);return new Date(a,b-1,c)}
function iso(d){return`${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`}
function diff(a,b){return Math.floor((Date.UTC(a.getFullYear(),a.getMonth(),a.getDate())-Date.UTC(b.getFullYear(),b.getMonth(),b.getDate()))/864e5)}
function add(d,n){const x=new Date(d);x.setDate(x.getDate()+n);return x}
function fmt(d){return new Intl.DateTimeFormat('ko-KR',{year:'numeric',month:'long',day:'numeric',weekday:'short'}).format(d)}
function shortFmt(d){return`${d.getMonth()+1}.${d.getDate()}`}
function isRestWeekday(d){return S.restDays.includes(d.getDay())}
function isManualPostponed(d){return!!S.postponedDates[iso(d)]}
function isSkipped(d){return isRestWeekday(d)||isManualPostponed(d)}
function nextStudyDate(d){let x=add(d,1);while(isSkipped(x))x=add(x,1);return x}
function activeIndex(d,startDate){const start=date(startDate);if(d<start||isSkipped(d))return null;let idx=-1,cur=new Date(start);while(cur<=d){if(!isSkipped(cur))idx++;cur=add(cur,1)}return idx}
function writtenIndex(d){return activeIndex(d,S.startDate)}
function practicalIndex(d){return S.practicalStartDate?activeIndex(d,S.practicalStartDate):null}
function writtenCycle(d){const i=writtenIndex(d);return i===null?null:i%4}
function practicalCycle(d){const i=practicalIndex(d);return i===null?null:i%4}
function targetRounds(s){return s.theoryTotal?Math.max(1,Number(s.targetRounds)||1):1}
function writtenTasks(s){const tasks=[];
  for(let l=1;l<=Number(s.specialTotal||0);l++)tasks.push({phase:'written',section:'특강',type:'special',round:1,lecture:l,duration:35});
  if(s.theoryTotal)for(let r=1;r<=targetRounds(s);r++)for(let l=1;l<=s.theoryTotal;l++)tasks.push({phase:'written',section:'필기이론+문제풀이',type:'theory',round:r,lecture:l,duration:40});
  for(let l=1;l<=Number(s.coreTotal||0);l++)tasks.push({phase:'written',section:'필기 핵심정리',type:'core',round:1,lecture:l,duration:43});
  return tasks;
}
function practicalTasks(s){const tasks=[];
  for(let l=1;l<=Number(s.theoryTotal||0);l++)tasks.push({phase:'practical',section:'실기이론+문제풀이',type:'theory',round:1,lecture:l,duration:38});
  for(let l=1;l<=Number(s.coreTotal||0);l++)tasks.push({phase:'practical',section:'실기 핵심정리',type:'core',round:1,lecture:l,duration:38});
  return tasks;
}
function taskKey(s,t){if(t.phase==='written')return t.type==='theory'?`w:${s.id}:theory:r${t.round}:l${t.lecture}`:`w:${s.id}:${t.type}:l${t.lecture}`;return`p:${s.id}:${t.type}:l${t.lecture}`}
function isTaskChecked(s,t){return!!S.checks[taskKey(s,t)]}
function setTaskChecked(s,t,on,studyDate){const k=taskKey(s,t);if(on)S.checks[k]={checkedAt:new Date().toISOString(),studyDate};else delete S.checks[k];save();maybeUnlockPractical(studyDate);render()}
function streamRange(stream,per,session){const start=session*per;if(start>=stream.length)return[];return stream.slice(start,Math.min(start+per,stream.length))}
function writtenRange(s,d){const i=writtenIndex(d);if(i===null||i%4!==s.day)return null;return streamRange(writtenTasks(s),s.per,Math.floor(i/4))}
function practicalRange(s,d){const i=practicalIndex(d);if(i===null||i%4!==s.day)return null;return streamRange(practicalTasks(s),s.per,Math.floor(i/4))}
function taskLabel(t){if(t.type==='theory'&&t.phase==='written')return`${t.section} · ${t.round}회독 ${t.lecture}강`;return`${t.section} · ${t.lecture}강`}
function taskRangeText(tasks){if(!tasks.length)return'';const groups=[];tasks.forEach(t=>{let g=groups.at(-1);const sig=`${t.section}|${t.round}`;if(!g||g.sig!==sig){g={sig,section:t.section,round:t.round,lectures:[]};groups.push(g)}g.lectures.push(t.lecture)});return groups.map(g=>{const a=g.lectures[0],b=g.lectures.at(-1),range=a===b?`${a}강`:`${a}~${b}강`;return g.section==='필기이론+문제풀이'?`${g.section} ${g.round}회독 ${range}`:`${g.section} ${range}`}).join(' · ')}
function taskMinutes(t){return Math.round(t.duration/1.5)}
function allWrittenChecked(){return S.subjects.every(s=>writtenTasks(s).every(t=>isTaskChecked(s,t)))}
function allPracticalChecked(){return S.practicalSubjects.every(s=>practicalTasks(s).every(t=>isTaskChecked(s,t)))}
function maybeUnlockPractical(studyDate){if(S.practicalStartDate||!allWrittenChecked())return;const base=date(studyDate||iso(new Date()));S.practicalStartDate=iso(nextStudyDate(base));save()}
function phaseForDate(d){return S.practicalStartDate&&d>=date(S.practicalStartDate)?'practical':'written'}
function scheduledForDate(d){const phase=phaseForDate(d),items=[];if(isSkipped(d))return{phase,cycle:null,items,review:false};if(phase==='written'){
  const c=writtenCycle(d);if(c===3)return{phase,cycle:c,items,review:true};S.subjects.filter(s=>s.day===c).forEach(s=>{const tasks=writtenRange(s,d);if(tasks&&tasks.length)items.push({s,tasks})});return{phase,cycle:c,items,review:false};
}
  const c=practicalCycle(d);if(c===3)return{phase,cycle:c,items,review:true};S.practicalSubjects.filter(s=>s.day===c).forEach(s=>{const tasks=practicalRange(s,d);if(tasks&&tasks.length)items.push({s,tasks})});return{phase,cycle:c,items,review:false};
}
function carry(d){const out=[],cur=date(S.startDate);while(cur<d){const plan=scheduledForDate(cur);plan.items.forEach(x=>{const left=x.tasks.filter(t=>!isTaskChecked(x.s,t));if(left.length)out.push({s:x.s,date:new Date(cur),tasks:left,phase:plan.phase})});cur.setDate(cur.getDate()+1)}return out}
function reviewSubjects(phase){return phase==='written'?S.subjects:S.practicalSubjects}
function info(d){const plan=scheduledForDate(d),co=carry(d),coCount=co.reduce((a,x)=>a+x.tasks.length,0);if(plan.cycle===null)return{...plan,co,total:coCount,done:0};if(plan.review){const done=reviewSubjects(plan.phase).filter(s=>S.reviews[`${plan.phase}:${iso(d)}:${s.id}`]).length;return{...plan,co,total:reviewSubjects(plan.phase).length+coCount,done}}const all=plan.items.flatMap(x=>x.tasks.map(t=>({s:x.s,t})));return{...plan,co,total:all.length+coCount,done:all.filter(x=>isTaskChecked(x.s,x.t)).length}}
function subjectCard(s,tasks,meta,target,studyDate){const done=tasks.filter(t=>isTaskChecked(s,t)).length,c=document.createElement('div');c.className='subject '+(done===tasks.length?'done':'');c.style.setProperty('--subject-color',s.color);c.innerHTML=`<div class="row"><div><h3>${s.name}</h3><div class="muted">${meta}</div></div><b>${done}/${tasks.length}</b></div><div class="checks"></div><div class="actions"><button class="primary all">모두 체크</button><button class="light clear">전체 해제</button></div>`;const list=c.querySelector('.checks');tasks.forEach(t=>{const on=isTaskChecked(s,t),l=document.createElement('label');l.className='check '+(on?'on':'');l.style.setProperty('--subject-color',s.color);l.innerHTML=`<input type="checkbox" ${on?'checked':''}><span class="box">${on?'✓':''}</span><span>${taskLabel(t)}</span><small class="muted">약 ${taskMinutes(t)}분</small>`;l.querySelector('input').onchange=e=>setTaskChecked(s,t,e.target.checked,studyDate);list.appendChild(l)});c.querySelector('.all').onclick=()=>{tasks.forEach(t=>S.checks[taskKey(s,t)]={checkedAt:new Date().toISOString(),studyDate});save();maybeUnlockPractical(studyDate);render()};c.querySelector('.clear').onclick=()=>{tasks.forEach(t=>delete S.checks[taskKey(s,t)]);save();render()};target.appendChild(c)}
function courseTotals(){const written=S.subjects.reduce((a,s)=>a+writtenTasks(s).length,0),practical=S.practicalSubjects.reduce((a,s)=>a+practicalTasks(s).length,0);return{written,practical,total:written+practical}}
function checkedCountForSubject(s,phase){const tasks=phase==='written'?writtenTasks(s):practicalTasks(s);return tasks.filter(t=>isTaskChecked(s,t)).length}
function header(){const d=date(selectedDate),n=diff(date(S.examDate),new Date()),i=info(d),tot=courseTotals(),done=S.subjects.reduce((a,s)=>a+checkedCountForSubject(s,'written'),0)+S.practicalSubjects.reduce((a,s)=>a+checkedCountForSubject(s,'practical'),0);$('dday').childNodes[0].nodeValue=(n>=0?'D-':'D+')+Math.abs(n);$('examLabel').textContent=S.examDate.replaceAll('-','.');$('startStat').textContent=S.startDate.slice(5).replace('-','.');$('todayStat').textContent=i.done+'/'+i.total;$('allStat').textContent=tot.total?Math.round(done/tot.total*100)+'%':'0%'}
function selected(){const d=date(selectedDate),st=date(S.startDate),i=info(d),box=$('todayContent');$('selectedDate').value=selectedDate;$('todayDate').textContent=fmt(d);box.innerHTML='';if(d<st){$('todayTitle').textContent='공부 시작 전';$('cycleBadge').textContent='시작 D-'+diff(st,d);$('timeStat').textContent='0분';$('rateStat').textContent='0%';$('postponeBtn').classList.add('hidden');box.innerHTML=`<div class="empty">공부 시작일은 <b>${fmt(st)}</b>입니다.</div>`;return}
  $('postponeBtn').classList.remove('hidden');$('rateStat').textContent=(i.total?Math.round(i.done/i.total*100):0)+'%';const carryMinutes=i.co.reduce((a,x)=>a+x.tasks.reduce((m,t)=>m+taskMinutes(t),0),0),scheduledMinutes=i.items.reduce((a,x)=>a+x.tasks.reduce((m,t)=>m+taskMinutes(t),0),0),rest=isRestWeekday(d),manual=isManualPostponed(d),phaseName=i.phase==='written'?'필기':'실기';
  if(rest||manual){$('todayTitle').textContent=rest?'휴식일':'미룬 날';$('cycleBadge').textContent=rest?'정기 휴식':'일정 미룸';$('timeStat').textContent=(carryMinutes||0)+'분';$('postponeBtn').textContent=manual?'미루기 취소':'휴식일에는 일정 없음';$('postponeBtn').disabled=rest}
  else if(i.review){$('todayTitle').textContent=i.co.length?`${phaseName} 복습 + 이월`:`${phaseName} 전체 복습`;$('cycleBadge').textContent=`${phaseName} 4일차`;$('timeStat').textContent=`${60+carryMinutes}~${90+carryMinutes}분`;$('postponeBtn').textContent='이 날짜 일정 전체 미루기';$('postponeBtn').disabled=false}
  else{$('todayTitle').textContent=i.co.length?`${phaseName} 인강 + 이월`:`${phaseName} 인강`;$('cycleBadge').textContent=`${phaseName} ${i.cycle+1}일차`;$('timeStat').textContent=(scheduledMinutes+carryMinutes)+'분';$('postponeBtn').textContent='이 날짜 일정 전체 미루기';$('postponeBtn').disabled=false}
  if(i.phase==='written'&&!S.practicalStartDate){const n=document.createElement('div');n.className='notice';n.innerHTML='<b>현재 필기 단계</b><br>특강 → 필기이론+문제풀이 → 필기 핵심정리 순서로 진행되며, 6과목 필기가 모두 끝나면 실기가 자동으로 열립니다.';box.appendChild(n)}
  if(i.phase==='practical'){const n=document.createElement('div');n.className='notice';n.innerHTML='<b>실기 단계 진행 중</b><br>토목적산 → 토목시공 → 토목공정 → 전체 복습 순환으로 진행됩니다.';box.appendChild(n)}
  if(i.co.length){const count=i.co.reduce((a,x)=>a+x.tasks.length,0),h=document.createElement('div');h.className='carry-title '+(count>=6?'danger':'');h.innerHTML=`<div class="row"><div><b>이월된 강의</b><div class="muted">이전에 못 들은 강의를 먼저 처리해요.</div></div>${count>=6?'<span class="pill-alert">이월 많음</span>':''}</div>`;box.appendChild(h);i.co.forEach(x=>subjectCard(x.s,x.tasks,`이월 · ${fmt(x.date)} · ${taskRangeText(x.tasks)}`,box,selectedDate))}
  if(rest||manual){if(!i.co.length)box.innerHTML+='<div class="empty">오늘은 쉬는 날입니다.</div>';return}
  if(i.review){const subjects=reviewSubjects(i.phase),r=document.createElement('div');r.className='subject review';r.style.setProperty('--subject-color','#9c7a10');r.innerHTML=`<h3>${phaseName} 전체 복습</h3><div class="muted">요약 노트와 틀린 문제를 확인한 뒤 체크하세요.</div><div class="checks"></div>`;const list=r.querySelector('.checks');subjects.forEach(s=>{const k=`${i.phase}:${selectedDate}:${s.id}`,on=!!S.reviews[k],l=document.createElement('label');l.className='check '+(on?'on':'');l.style.setProperty('--subject-color',s.color);l.innerHTML=`<input type="checkbox" ${on?'checked':''}><span class="box">${on?'✓':''}</span><span>${s.name}</span>`;l.querySelector('input').onchange=e=>{e.target.checked?S.reviews[k]=1:delete S.reviews[k];save();render()};list.appendChild(l)});box.appendChild(r);return}
  i.items.forEach(x=>subjectCard(x.s,x.tasks,`${taskRangeText(x.tasks)} · 1.5배속`,box,selectedDate));if(!i.co.length&&!i.items.length)box.innerHTML+='<div class="empty">이 단계의 배정 강의를 모두 완료했습니다.</div>'
}
function currentTaskInfo(s,phase){const tasks=phase==='written'?writtenTasks(s):practicalTasks(s),done=tasks.filter(t=>isTaskChecked(s,t)).length,next=tasks.find(t=>!isTaskChecked(s,t));return{done,total:tasks.length,next,complete:done===tasks.length}}
function progress(){const p=$('progress');p.innerHTML='';const h1=document.createElement('div');h1.className='carry-title';h1.innerHTML='<b>필기 과정</b><div class="muted">특강 → 필기이론 회독 → 필기 핵심정리</div>';p.appendChild(h1);S.subjects.forEach(s=>{const x=currentTaskInfo(s,'written'),pc=x.total?Math.round(x.done/x.total*100):0,row=document.createElement('div');row.className='progress';row.style.setProperty('--subject-color',s.color);row.innerHTML=`<div class="prow"><span>${s.name}</span><span>${x.complete?'필기 완료':x.next?taskLabel(x.next):'-'}</span></div><div class="muted" style="margin-top:4px">${x.done}/${x.total}개 · 필기이론 목표 ${targetRounds(s)}회독</div><div class="bar"><i style="width:${pc}%"></i></div>`;p.appendChild(row)});
  const h2=document.createElement('div');h2.className='carry-title';h2.innerHTML=`<b>실기 과정</b><div class="muted">${S.practicalStartDate?`시작일 ${S.practicalStartDate}`:'필기 완료 후 자동 시작'}</div>`;p.appendChild(h2);S.practicalSubjects.forEach(s=>{const x=currentTaskInfo(s,'practical'),pc=x.total?Math.round(x.done/x.total*100):0,row=document.createElement('div');row.className='progress';row.style.setProperty('--subject-color',s.color);row.innerHTML=`<div class="prow"><span>${s.name}</span><span>${x.complete?'실기 완료':S.practicalStartDate&&x.next?taskLabel(x.next):'잠금'}</span></div><div class="muted" style="margin-top:4px">${x.done}/${x.total}개</div><div class="bar"><i style="width:${pc}%"></i></div>`;p.appendChild(row)})
}
function schedule(){const l=$('scheduleList'),from=date($('scheduleFrom').value||S.startDate),days=+$('scheduleDays').value;l.innerHTML='';for(let i=0;i<days;i++){const d=add(from,i),plan=scheduledForDate(d),rest=isRestWeekday(d),manual=isManualPostponed(d),phaseName=plan.phase==='written'?'필기':'실기',x=document.createElement('div');x.className='schedule '+(rest?'rest':manual?'postponed':plan.review?'review':'');x.innerHTML=`<div class="row"><b>${fmt(d)}</b><span>${rest?'휴식':manual?'미룸':plan.review?phaseName+' 복습':phaseName+' '+(plan.cycle+1)+'일차'}</span></div><div class="chips"></div>`;const ch=x.querySelector('.chips');if(rest)ch.innerHTML='<span class="chip">정기 휴식일</span>';else if(manual)ch.innerHTML='<span class="chip">일정 전체 미룸</span>';else if(plan.review)ch.innerHTML=`<span class="chip">${phaseName} 전체 복습</span>`;else if(!plan.items.length)ch.innerHTML='<span class="chip">배정 완료</span>';else plan.items.forEach(({s,tasks})=>ch.innerHTML+=`<span class="chip" style="background:${s.color}18;color:${s.color}">${s.name} · ${taskRangeText(tasks)}</span>`);l.appendChild(x)}}
function weekBounds(){const t=new Date(),day=t.getDay(),monday=add(t,-((day+6)%7)),sunday=add(monday,6);return{monday,sunday}}
function weeklyStats(){const{monday,sunday}=weekBounds();$('weekRange').textContent=`${shortFmt(monday)} ~ ${shortFmt(sunday)}`;const counts={},entries=[];Object.entries(S.checks).forEach(([k,v])=>{if(!v||typeof v!=='object'||!v.studyDate)return;const d=date(v.studyDate);if(d>=date(iso(monday))&&d<=date(iso(sunday))){const id=k.split(':')[1];entries.push({id,k});counts[id]=(counts[id]||0)+1}});const total=entries.length,minutes=Math.round(total*27),allSubjects=[...S.subjects,...S.practicalSubjects],topId=Object.keys(counts).sort((a,b)=>counts[b]-counts[a])[0],top=allSubjects.find(s=>s.id===topId);$('weekLectures').textContent=total+'강';$('weekTime').textContent=minutes>=60?`${Math.floor(minutes/60)}시간 ${minutes%60}분`:minutes+'분';$('weekTop').textContent=top?`${top.name} ${counts[topId]}강`:'-';$('overdueCount').textContent=carry(new Date()).reduce((a,x)=>a+x.tasks.length,0)+'강'}
function plannedFinishDate(s,phase){const stream=phase==='written'?writtenTasks(s):practicalTasks(s),start=phase==='written'?S.startDate:S.practicalStartDate;if(!start)return null;const remaining=Math.max(0,stream.length-stream.filter(t=>isTaskChecked(s,t)).length);if(!remaining)return'완료';let sessions=Math.ceil(remaining/s.per),d=new Date()<date(start)?date(start):new Date();for(let i=0;i<4000;i++,d=add(d,1)){const plan=scheduledForDate(d);if(plan.phase===phase&&plan.items.some(x=>x.s.id===s.id)){sessions--;if(sessions<=0)return fmt(d)}}return'계산 불가'}
function records(){weeklyStats();const est=$('estimates');est.innerHTML='';S.subjects.forEach(s=>{const x=document.createElement('div');x.className='estimate';x.innerHTML=`<span><b style="color:${s.color}">●</b> ${s.name}<small class="muted" style="display:block;margin-left:17px">필기 과정</small></span><b>${plannedFinishDate(s,'written')||'-'}</b>`;est.appendChild(x)});S.practicalSubjects.forEach(s=>{const x=document.createElement('div');x.className='estimate';x.innerHTML=`<span><b style="color:${s.color}">●</b> ${s.name}<small class="muted" style="display:block;margin-left:17px">실기 과정</small></span><b>${plannedFinishDate(s,'practical')||'필기 완료 후'}</b>`;est.appendChild(x)});const notes=$('notes');notes.innerHTML='';[...S.subjects,...S.practicalSubjects].forEach(s=>{const x=document.createElement('div');x.className='note-card';x.style.setProperty('--subject-color',s.color);x.innerHTML=`<b>${s.name}</b><div class="field"><textarea placeholder="공식, 이해 안 된 부분, 다시 볼 강의 등을 적어두세요.">${S.notes[s.id]||''}</textarea></div>`;x.querySelector('textarea').oninput=e=>{S.notes[s.id]=e.target.value;save()};notes.appendChild(x)})}
function colorFields(s,i,prefix){return`<div class="field color-row"><div><label>색상 코드</label><input value="${s.color}" data-group="${prefix}" data-i="${i}" data-f="color"></div><div><label>선택</label><input type="color" value="${s.color}" data-group="${prefix}" data-i="${i}" data-f="colorPicker"></div></div>`}
function settings(){$('startDate').value=S.startDate;$('examDate').value=S.examDate;const rd=$('restDays'),names=['일','월','화','수','목','금','토'];rd.innerHTML='';names.forEach((name,i)=>{const b=document.createElement('button');b.type='button';b.className='rest-day '+(S.restDays.includes(i)?'on':'');b.textContent=name;b.dataset.day=i;b.onclick=()=>{const day=+b.dataset.day;S.restDays.includes(day)?S.restDays=S.restDays.filter(x=>x!==day):S.restDays.push(day);save();render()};rd.appendChild(b)});
  const w=$('subjectSettings');w.innerHTML='<div class="carry-title"><b>필기 과정 설정</b></div>';S.subjects.forEach((s,i)=>{const x=document.createElement('div');x.className='setting';x.innerHTML=`<div class="row"><h3>${s.name}</h3><span class="chip" style="background:${s.color}18;color:${s.color}">${s.specialTotal?'특강 포함':'필기'}</span></div><div class="grid"><div class="field"><label>필기이론 총 강의 수</label><input type="number" min="1" value="${s.theoryTotal??''}" data-group="written" data-i="${i}" data-f="theoryTotal"></div><div class="field"><label>필기이론 목표 회독</label><input type="number" min="1" max="10" value="${targetRounds(s)}" data-group="written" data-i="${i}" data-f="targetRounds"></div></div><div class="grid"><div class="field"><label>특강 강의 수</label><input type="number" min="0" value="${s.specialTotal}" data-group="written" data-i="${i}" data-f="specialTotal"></div><div class="field"><label>필기 핵심정리 강의 수</label><input type="number" min="0" value="${s.coreTotal}" data-group="written" data-i="${i}" data-f="coreTotal"></div></div><div class="field"><label>해당 날짜 강의 수</label><select data-group="written" data-i="${i}" data-f="per"><option value="2" ${s.per===2?'selected':''}>2강</option><option value="3" ${s.per===3?'selected':''}>3강</option><option value="4" ${s.per===4?'selected':''}>4강</option></select></div>${colorFields(s,i,'written')}`;wireColors(x);w.appendChild(x)});
  const p=document.createElement('div');p.className='carry-title';p.innerHTML='<b>실기 과정 설정</b><div class="muted">필기 전체 완료 후 자동 시작</div>';w.appendChild(p);S.practicalSubjects.forEach((s,i)=>{const x=document.createElement('div');x.className='setting';x.innerHTML=`<div class="row"><h3>${s.name}</h3><span class="chip" style="background:${s.color}18;color:${s.color}">실기</span></div><div class="grid"><div class="field"><label>실기이론+문제풀이</label><input type="number" min="0" value="${s.theoryTotal}" data-group="practical" data-i="${i}" data-f="theoryTotal"></div><div class="field"><label>실기 핵심정리</label><input type="number" min="0" value="${s.coreTotal}" data-group="practical" data-i="${i}" data-f="coreTotal"></div></div><div class="field"><label>해당 날짜 강의 수</label><select data-group="practical" data-i="${i}" data-f="per"><option value="2" ${s.per===2?'selected':''}>2강</option><option value="3" ${s.per===3?'selected':''}>3강</option><option value="4" ${s.per===4?'selected':''}>4강</option></select></div>${colorFields(s,i,'practical')}`;wireColors(x);w.appendChild(x)})}
function wireColors(x){const text=x.querySelector('[data-f=color]'),picker=x.querySelector('[data-f=colorPicker]');picker.oninput=()=>text.value=picker.value;text.oninput=()=>{if(/^#[0-9a-fA-F]{6}$/.test(text.value))picker.value=text.value}}
function hasAnyChecksForDate(d){const plan=scheduledForDate(d);if(plan.review)return reviewSubjects(plan.phase).some(s=>S.reviews[`${plan.phase}:${iso(d)}:${s.id}`]);return plan.items.some(x=>x.tasks.some(t=>isTaskChecked(x.s,t)))}
function postponeSelected(){const d=date(selectedDate);if(isRestWeekday(d))return;if(isManualPostponed(d)){delete S.postponedDates[selectedDate];save();render();return}if(hasAnyChecksForDate(d)){alert('이미 체크한 강의가 있어요. 체크를 먼저 해제한 뒤 미뤄주세요.');return}if(confirm(`${fmt(d)} 일정을 전부 다음 공부일로 미룰까요?`)){S.postponedDates[selectedDate]=true;save();render()}}
function render(){maybeUnlockPractical(selectedDate);header();selected();progress();schedule();records();settings()}
document.querySelectorAll('.nav button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.nav button,.view').forEach(x=>x.classList.remove('on'));b.classList.add('on');$(b.dataset.v).classList.add('on');scrollTo(0,0)});
$('selectedDate').onchange=e=>{selectedDate=e.target.value;render()};$('prevDate').onclick=()=>{selectedDate=iso(add(date(selectedDate),-1));render()};$('nextDate').onclick=()=>{selectedDate=iso(add(date(selectedDate),1));render()};$('jumpToday').onclick=()=>{selectedDate=iso(new Date());render()};$('postponeBtn').onclick=postponeSelected;$('showSchedule').onclick=schedule;
$('saveBtn').onclick=()=>{S.startDate=$('startDate').value||DEF.startDate;S.examDate=$('examDate').value||DEF.examDate;document.querySelectorAll('[data-group][data-i]').forEach(e=>{const arr=e.dataset.group==='written'?S.subjects:S.practicalSubjects,i=+e.dataset.i,f=e.dataset.f;if(f==='colorPicker')return;if(f==='color')arr[i][f]=e.value;else if(f==='targetRounds')arr[i][f]=Math.max(1,Math.min(10,Number(e.value)||1));else arr[i][f]=e.value===''?null:+e.value});save();render();alert('설정을 저장했어요.')};
$('resetBtn').onclick=()=>{if(confirm('모든 필기·실기 강의 체크와 복습 체크를 초기화할까요? 메모와 설정은 유지됩니다.')){S.checks={};S.reviews={};S.practicalStartDate=null;save();render()}};
$('scheduleFrom').value=iso(new Date());
if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js?v=5').catch(()=>{});
save();render();
