const DEFAULT_COLORS=['#2878c8','#8b5cf6','#15a06b','#e29b20','#df5b57','#537188'];
const DEF={startDate:'2026-07-01',examDate:'2027-01-01',subjects:[{id:'hydro',name:'수리수문학',total:45,per:3,day:0,color:DEFAULT_COLORS[0]},{id:'soil',name:'토질 및 기초',total:46,per:3,day:0,color:DEFAULT_COLORS[1]},{id:'water',name:'상하수도공학',total:29,per:2,day:1,color:DEFAULT_COLORS[2]},{id:'survey',name:'측량학',total:42,per:3,day:1,color:DEFAULT_COLORS[3]},{id:'mech',name:'응용역학',total:53,per:3,day:2,color:DEFAULT_COLORS[4]},{id:'struct',name:'철근콘크리트 및 강구조',total:null,per:3,day:2,color:DEFAULT_COLORS[5]}],checks:{},reviews:{},notes:{},restDays:[],postponedDates:{}};
const K='civilPlannerWeb1',$=id=>document.getElementById(id),pad=n=>String(n).padStart(2,'0');
function clone(x){return JSON.parse(JSON.stringify(x))}
let S=(()=>{try{const raw=JSON.parse(localStorage.getItem(K));if(!raw)return clone(DEF);const merged={...clone(DEF),...raw,checks:raw.checks||{},reviews:raw.reviews||{},notes:raw.notes||{},restDays:raw.restDays||[],postponedDates:raw.postponedDates||{}};merged.subjects=(raw.subjects||clone(DEF.subjects)).map((s,i)=>({...clone(DEF.subjects[i]||{}),...s,color:s.color||DEFAULT_COLORS[i%DEFAULT_COLORS.length]}));return merged}catch{return clone(DEF)}})();
let selectedDate=iso(new Date());
const save=()=>localStorage.setItem(K,JSON.stringify(S));
function date(s){const[a,b,c]=s.split('-').map(Number);return new Date(a,b-1,c)}function iso(d){return`${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`}function diff(a,b){return Math.floor((Date.UTC(a.getFullYear(),a.getMonth(),a.getDate())-Date.UTC(b.getFullYear(),b.getMonth(),b.getDate()))/864e5)}function add(d,n){const x=new Date(d);x.setDate(x.getDate()+n);return x}function fmt(d){return new Intl.DateTimeFormat('ko-KR',{year:'numeric',month:'long',day:'numeric',weekday:'short'}).format(d)}function shortFmt(d){return`${d.getMonth()+1}.${d.getDate()}`}
function isRestWeekday(d){return S.restDays.includes(d.getDay())}function isManualPostponed(d){return!!S.postponedDates[iso(d)]}function isSkipped(d){return isRestWeekday(d)||isManualPostponed(d)}
function studyIndex(d){const start=date(S.startDate);if(d<start||isSkipped(d))return null;let idx=-1,cur=new Date(start);while(cur<=d){if(!isSkipped(cur))idx++;cur.setDate(cur.getDate()+1)}return idx}
function cycle(d){const i=studyIndex(d);return i===null?null:i%4}
function range(s,d){const i=studyIndex(d);if(i===null||i%4!==s.day)return null;const session=Math.floor(i/4),a=session*s.per+1,b=s.total?Math.min(a+s.per-1,s.total):a+s.per-1;if(s.total&&a>s.total)return[];return Array.from({length:b-a+1},(_,k)=>a+k)}
function key(id,n){return id+':'+n}function isChecked(id,n){return!!S.checks[key(id,n)]}function setCheck(id,n,on,studyDate){if(on)S.checks[key(id,n)]={checkedAt:new Date().toISOString(),studyDate};else delete S.checks[key(id,n)];save();render()}function checkedCount(s){return Object.keys(S.checks).filter(k=>k.startsWith(s.id+':')).length}
function carry(d){const out=[],cur=date(S.startDate);while(cur<d){const c=cycle(cur);if(c!==null&&c!==3)S.subjects.filter(s=>s.day===c).forEach(s=>{const r=range(s,cur);if(!r||!r.length)return;const left=r.filter(n=>!isChecked(s.id,n));if(left.length)out.push({s,date:new Date(cur),lectures:left})});cur.setDate(cur.getDate()+1)}return out}
function info(d){const c=cycle(d),co=carry(d),coCount=co.reduce((a,x)=>a+x.lectures.length,0);if(c===null)return{c,total:coCount,done:0,subs:[],co};if(c===3){const done=S.subjects.filter(s=>S.reviews[iso(d)+':'+s.id]).length;return{c,total:6+coCount,done,subs:[],co}}const subs=S.subjects.filter(s=>s.day===c).map(s=>({s,r:range(s,d)})).filter(x=>x.r&&x.r.length),all=subs.flatMap(x=>x.r.map(n=>key(x.s.id,n)));return{c,total:all.length+coCount,done:all.filter(k=>S.checks[k]).length,subs,co}}
function subjectCard(s,lectures,meta,target,studyDate){const done=lectures.filter(n=>isChecked(s.id,n)).length,c=document.createElement('div');c.className='subject '+(done===lectures.length?'done':'');c.style.setProperty('--subject-color',s.color);c.innerHTML=`<div class="row"><div><h3>${s.name}</h3><div class="muted">${meta}</div></div><b>${done}/${lectures.length}</b></div><div class="checks"></div><div class="actions"><button class="primary all">모두 체크</button><button class="light clear">전체 해제</button></div>`;const list=c.querySelector('.checks');lectures.forEach(n=>{const on=isChecked(s.id,n),l=document.createElement('label');l.className='check '+(on?'on':'');l.style.setProperty('--subject-color',s.color);l.innerHTML=`<input type="checkbox" ${on?'checked':''}><span class="box">${on?'✓':''}</span><span>${n}강 인강</span><small class="muted">약 27분</small>`;l.querySelector('input').onchange=e=>setCheck(s.id,n,e.target.checked,studyDate);list.appendChild(l)});c.querySelector('.all').onclick=()=>{lectures.forEach(n=>S.checks[key(s.id,n)]={checkedAt:new Date().toISOString(),studyDate});save();render()};c.querySelector('.clear').onclick=()=>{lectures.forEach(n=>delete S.checks[key(s.id,n)]);save();render()};target.appendChild(c)}
function header(){const d=date(selectedDate),exam=date(S.examDate),n=diff(exam,new Date()),i=info(d),known=S.subjects.filter(s=>s.total),total=known.reduce((a,s)=>a+s.total,0),done=known.reduce((a,s)=>a+Math.min(checkedCount(s),s.total),0);$('dday').childNodes[0].nodeValue=(n>=0?'D-':'D+')+Math.abs(n);$('examLabel').textContent=S.examDate.replaceAll('-','.');$('startStat').textContent=S.startDate.slice(5).replace('-','.');$('todayStat').textContent=i.done+'/'+i.total;$('allStat').textContent=total?Math.round(done/total*100)+'%':'0%'}
function selected(){const d=date(selectedDate),st=date(S.startDate),i=info(d),box=$('todayContent');$('selectedDate').value=selectedDate;$('todayDate').textContent=fmt(d);box.innerHTML='';if(d<st){$('todayTitle').textContent='공부 시작 전';$('cycleBadge').textContent='시작 D-'+diff(st,d);$('timeStat').textContent='0분';$('rateStat').textContent='0%';$('postponeBtn').classList.add('hidden');box.innerHTML=`<div class="empty">공부 시작일은 <b>${fmt(st)}</b>입니다.</div>`;return}$('postponeBtn').classList.remove('hidden');$('rateStat').textContent=(i.total?Math.round(i.done/i.total*100):0)+'%';const coCount=i.co.reduce((a,x)=>a+x.lectures.length,0),rest=isRestWeekday(d),manual=isManualPostponed(d);if(rest||manual){$('todayTitle').textContent=rest?'휴식일':'미룬 날';$('cycleBadge').textContent=rest?'정기 휴식':'일정 미룸';$('timeStat').textContent=coCount?Math.round(coCount*40/1.5)+'분':'0분';$('postponeBtn').textContent=manual?'미루기 취소':'휴식일에는 일정 없음';$('postponeBtn').disabled=rest}else if(i.c===3){$('todayTitle').textContent=i.co.length?'전체 복습 + 이월 강의':'전체 복습';$('cycleBadge').textContent='4일차';$('timeStat').textContent=`${60+coCount*27}~${90+coCount*27}분`;$('postponeBtn').textContent='이 날짜 일정 전체 미루기';$('postponeBtn').disabled=false}else{$('todayTitle').textContent=i.co.length?'오늘 할 인강 + 이월':'오늘 할 인강';$('cycleBadge').textContent=(i.c+1)+'일차';$('timeStat').textContent=Math.round(i.total*40/1.5)+'분';$('postponeBtn').textContent='이 날짜 일정 전체 미루기';$('postponeBtn').disabled=false}
if(i.co.length){const h=document.createElement('div');h.className='carry-title '+(coCount>=6?'danger':'');h.innerHTML=`<div class="row"><div><b>이월된 강의</b><div class="muted">먼저 처리하면 일정이 덜 밀려요.</div></div>${coCount>=6?'<span class="pill-alert">이월 많음</span>':''}</div>`;box.appendChild(h);i.co.forEach(x=>subjectCard(x.s,x.lectures,`이월 · ${fmt(x.date)} · ${x.lectures[0]}~${x.lectures.at(-1)}강`,box,selectedDate))}
if(rest||manual){if(!i.co.length)box.innerHTML+='<div class="empty">오늘은 쉬는 날입니다.</div>';return}
if(i.c===3){const r=document.createElement('div');r.className='subject review';r.style.setProperty('--subject-color','#9c7a10');r.innerHTML='<h3>6과목 전체 복습</h3><div class="muted">공식·요약·틀린 문제를 확인한 뒤 체크하세요.</div><div class="checks"></div>';const list=r.querySelector('.checks');S.subjects.forEach(s=>{const k=selectedDate+':'+s.id,on=!!S.reviews[k],l=document.createElement('label');l.className='check '+(on?'on':'');l.style.setProperty('--subject-color',s.color);l.innerHTML=`<input type="checkbox" ${on?'checked':''}><span class="box">${on?'✓':''}</span><span>${s.name}</span>`;l.querySelector('input').onchange=e=>{e.target.checked?S.reviews[k]=1:delete S.reviews[k];save();render()};list.appendChild(l)});box.appendChild(r);return}
i.subs.forEach(x=>subjectCard(x.s,x.r,`${x.r[0]}~${x.r.at(-1)}강 · 1.5배속`,box,selectedDate));if(!i.co.length&&!i.subs.length)box.innerHTML='<div class="empty">배정 과목은 모두 완강했습니다.</div>'}
function progress(){const p=$('progress');p.innerHTML='';S.subjects.forEach(s=>{const d=checkedCount(s),pc=s.total?Math.round(Math.min(d,s.total)/s.total*100):0,x=document.createElement('div');x.className='progress';x.style.setProperty('--subject-color',s.color);x.innerHTML=`<div class="prow"><span>${s.name}</span><span>${s.total?Math.min(d,s.total)+'/'+s.total+'강':d+'강 체크'}</span></div><div class="bar"><i style="width:${pc}%"></i></div>`;p.appendChild(x)})}
function schedule(){const l=$('scheduleList'),from=date($('scheduleFrom').value||S.startDate),days=+$('scheduleDays').value;l.innerHTML='';for(let i=0;i<days;i++){const d=add(from,i),c=cycle(d),rest=isRestWeekday(d),manual=isManualPostponed(d),x=document.createElement('div');x.className='schedule '+(rest?'rest':manual?'postponed':c===3?'review':'');x.innerHTML=`<div class="row"><b>${fmt(d)}</b><span>${rest?'휴식':manual?'미룸':c===3?'복습':(c+1)+'일차'}</span></div><div class="chips"></div>`;const ch=x.querySelector('.chips');if(rest)ch.innerHTML='<span class="chip">정기 휴식일</span>';else if(manual)ch.innerHTML='<span class="chip">일정 전체 미룸</span>';else if(c===3)ch.innerHTML='<span class="chip">6과목 전체 복습</span>';else S.subjects.filter(s=>s.day===c).forEach(s=>{const r=range(s,d);if(r&&r.length)ch.innerHTML+=`<span class="chip" style="background:${s.color}18;color:${s.color}">${s.name} ${r[0]}~${r.at(-1)}강</span>`});l.appendChild(x)}}
function weekBounds(){const t=new Date(),day=t.getDay(),monday=add(t,-((day+6)%7)),sunday=add(monday,6);return{monday,sunday}}
function weeklyStats(){const{monday,sunday}=weekBounds();$('weekRange').textContent=`${shortFmt(monday)} ~ ${shortFmt(sunday)}`;const counts={},entries=[];Object.entries(S.checks).forEach(([k,v])=>{if(!v||typeof v!=='object'||!v.studyDate)return;const d=date(v.studyDate);if(d>=date(iso(monday))&&d<=date(iso(sunday))){const id=k.split(':')[0];entries.push({id,k});counts[id]=(counts[id]||0)+1}});const total=entries.length,minutes=Math.round(total*40/1.5),topId=Object.keys(counts).sort((a,b)=>counts[b]-counts[a])[0],top=S.subjects.find(s=>s.id===topId);$('weekLectures').textContent=total+'강';$('weekTime').textContent=minutes>=60?`${Math.floor(minutes/60)}시간 ${minutes%60}분`:minutes+'분';$('weekTop').textContent=top?`${top.name} ${counts[topId]}강`:'-';$('overdueCount').textContent=carry(new Date()).reduce((a,x)=>a+x.lectures.length,0)+'강'}
function estimateDate(s){if(!s.total)return null;const remaining=Math.max(0,s.total-checkedCount(s));if(!remaining)return'완강';let sessions=Math.ceil(remaining/s.per),d=new Date()<date(S.startDate)?date(S.startDate):new Date();for(let i=0;i<1500;i++,d=add(d,1)){if(cycle(d)===s.day){sessions--;if(sessions<=0)return fmt(d)}}return'계산 불가'}
function records(){weeklyStats();const est=$('estimates');est.innerHTML='';S.subjects.forEach(s=>{const x=document.createElement('div');x.className='estimate';x.innerHTML=`<span><b style="color:${s.color}">●</b> ${s.name}</span><b>${estimateDate(s)||'총 강의 수 입력 필요'}</b>`;est.appendChild(x)});const notes=$('notes');notes.innerHTML='';S.subjects.forEach(s=>{const x=document.createElement('div');x.className='note-card';x.style.setProperty('--subject-color',s.color);x.innerHTML=`<b>${s.name}</b><div class="field"><textarea placeholder="공식, 이해 안 된 부분, 다시 볼 강의 등을 적어두세요.">${S.notes[s.id]||''}</textarea></div>`;x.querySelector('textarea').oninput=e=>{S.notes[s.id]=e.target.value;save()};notes.appendChild(x)})}
function settings(){$('startDate').value=S.startDate;$('examDate').value=S.examDate;const rd=$('restDays'),names=['일','월','화','수','목','금','토'];rd.innerHTML='';names.forEach((name,i)=>{const b=document.createElement('button');b.type='button';b.className='rest-day '+(S.restDays.includes(i)?'on':'');b.textContent=name;b.dataset.day=i;b.onclick=()=>{const day=+b.dataset.day;S.restDays.includes(day)?S.restDays=S.restDays.filter(x=>x!==day):S.restDays.push(day);save();render()};rd.appendChild(b)});const w=$('subjectSettings');w.innerHTML='';S.subjects.forEach((s,i)=>{const x=document.createElement('div');x.className='setting';x.innerHTML=`<div class="row"><h3>${s.name}</h3><span class="chip" style="background:${s.color}18;color:${s.color}">과목 색상</span></div><div class="grid"><div class="field"><label>총 강의 수</label><input type="number" min="1" value="${s.total??''}" data-i="${i}" data-f="total"></div><div class="field"><label>해당 날짜 강의 수</label><select data-i="${i}" data-f="per"><option value="2" ${s.per===2?'selected':''}>2강</option><option value="3" ${s.per===3?'selected':''}>3강</option></select></div></div><div class="field color-row"><div><label>색상 코드</label><input value="${s.color}" data-i="${i}" data-f="color"></div><div><label>선택</label><input type="color" value="${s.color}" data-i="${i}" data-f="colorPicker"></div></div>`;const text=x.querySelector('[data-f=color]'),picker=x.querySelector('[data-f=colorPicker]');picker.oninput=()=>text.value=picker.value;text.oninput=()=>{if(/^#[0-9a-fA-F]{6}$/.test(text.value))picker.value=text.value};w.appendChild(x)})}
function hasAnyChecksForDate(d){const c=cycle(d);if(c===null)return false;if(c===3)return S.subjects.some(s=>S.reviews[iso(d)+':'+s.id]);return S.subjects.filter(s=>s.day===c).some(s=>(range(s,d)||[]).some(n=>isChecked(s.id,n)))}
function postponeSelected(){const d=date(selectedDate);if(isRestWeekday(d))return;if(isManualPostponed(d)){delete S.postponedDates[selectedDate];save();render();return}if(hasAnyChecksForDate(d)){alert('이미 체크한 강의가 있어요. 체크를 먼저 해제한 뒤 미뤄주세요.');return}if(confirm(`${fmt(d)} 일정을 전부 다음 공부일로 미룰까요?`)){S.postponedDates[selectedDate]=true;save();render()}}
function render(){header();selected();progress();schedule();records();settings()}
document.querySelectorAll('.nav button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.nav button,.view').forEach(x=>x.classList.remove('on'));b.classList.add('on');$(b.dataset.v).classList.add('on');scrollTo(0,0)});
$('selectedDate').onchange=e=>{selectedDate=e.target.value;render()};$('prevDate').onclick=()=>{selectedDate=iso(add(date(selectedDate),-1));render()};$('nextDate').onclick=()=>{selectedDate=iso(add(date(selectedDate),1));render()};$('jumpToday').onclick=()=>{selectedDate=iso(new Date());render()};$('postponeBtn').onclick=postponeSelected;$('showSchedule').onclick=schedule;
$('saveBtn').onclick=()=>{S.startDate=$('startDate').value||DEF.startDate;S.examDate=$('examDate').value||DEF.examDate;document.querySelectorAll('[data-i]').forEach(e=>{const i=+e.dataset.i,f=e.dataset.f;if(f==='colorPicker')return;S.subjects[i][f]=f==='color'?e.value:(e.value===''?null:+e.value)});save();render();alert('설정을 저장했어요.')};$('resetBtn').onclick=()=>{if(confirm('모든 강의와 복습 체크를 초기화할까요? 메모와 설정은 유지됩니다.')){S.checks={};S.reviews={};save();render()}};
$('scheduleFrom').value=iso(new Date());
if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{});
render();